In [1]:
import numpy as np

In [8]:
# Mnozenje matrica

A = np.array([[2,3], [1,4]])
B = np.array([[1,2,1],[2,2,3]])
C = np.array([[3,1], [1,3]])

E = A * C #element po element
print(E)
print(E.shape, '\n')

D = A.dot(B) #matricno
print(D)
print(D.shape, '\n')

F = A.dot(C)
print(F)
print(F.shape, '\n')

G = np.dot(A,B)
print(F)
print(F.shape, '\n')

[[ 6  3]
 [ 1 12]]
(2, 2) 

[[ 8 10 11]
 [ 9 10 13]]
(2, 3) 

[[ 9 11]
 [ 7 13]]
(2, 2) 

[[ 9 11]
 [ 7 13]]
(2, 2) 



In [12]:
# Mnozenje jedinicnom matricom
I = np.eye(2)
print(A, '\n')
print(A*I, '\n')
print(A.dot(I))

[[2 3]
 [1 4]] 

[[2. 0.]
 [0. 4.]] 

[[2. 3.]
 [1. 4.]]


In [14]:
# Skalarno, vektorski i element po element 

v1 = np.array([[1],[1],[2],[1]])
v2 = np.array([[2],[2],[0],[1]])

print(np.dot(v1.T, v2)) #skalarno: vrsta*kolona
print(np.dot(v1, v2.T)) #vektorski: kolona*vrsta



[[5]]
[[2 2 0 1]
 [2 2 0 1]
 [4 4 0 2]
 [2 2 0 1]]


In [17]:
# Transponovanje matrica 

print(A, '\n')
print(A.T, '\n')
print(B, '\n')
print(B.T, '\n')
print(C, '\n')
print(C.T, '\n')

[[2 3]
 [1 4]] 

[[2 1]
 [3 4]] 

[[1 2 1]
 [2 2 3]] 

[[1 2]
 [2 2]
 [1 3]] 

[[3 1]
 [1 3]] 

[[3 1]
 [1 3]] 



In [21]:
# Izracunavanje traga matrice (suma elemenata na dijagonali)

print(A,'\n')
t = np.trace(A)
print(t, '\n')

d = np.diag(A)
t1 = sum(d)
print(d, '\n')
print(t1)

[[2 3]
 [1 4]] 

6 

[2 4] 

6


In [24]:
# Izracunavanje norme
print(v1, '\n')
print(np.linalg.norm(v1), '\n')
print(np.linalg.norm(v1,1), '\n')
print(np.linalg.norm(v1,2), '\n')
print(np.linalg.norm(v1,np.inf) )


[[1]
 [1]
 [2]
 [1]] 

2.6457513110645907 

5.0 

2.6457513110645907 

2.0


In [35]:
# Izracunati rastojanje i ugao

d = np.linalg.norm(v1 - v2)
e = np.dot(v1.T, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

print(d, '\n')
print(e)

2.449489742783178 

[[0.62994079]]


In [28]:
# Rang matrice

A = np.array([[1,0,5], [2,6,1], [3,2,0]])
B = np.array([[1,2,3], [0,2,2], [4,0,4]])

print(np.linalg.matrix_rank(A), '\n')
print(np.linalg.matrix_rank(B))

3 

2


In [37]:
# Inverzna matrica

print(np.linalg.inv(A)) #regularna
#print(np.linalg.inv(B)) --singularna


[[ 0.02777778 -0.13888889  0.41666667]
 [-0.04166667  0.20833333 -0.125     ]
 [ 0.19444444  0.02777778 -0.08333333]]


In [38]:
# Determinante matrice

print(np.linalg.det(A))
print(np.linalg.det(B))

-72.0
0.0


In [40]:
# Naci karakterisiticne vrednosti i karakterisitcne vektore matrice

A = np.array([[2,1],[1,2]])
B = np.array([[2,0,0], [0,3,4], [0,4,9]])
C, D = np.linalg.eig(A)

print(C, '\n')
print(D)

[3. 1.] 

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
