import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
#Varijable

num = 5
Num = 6
alpha = 'hello'
mix = str(num) + ' ' + alpha

print(num)
print(Num)
print(alpha)
print(mix)

5
6
hello
5 hello


In [28]:
#Liste, vektori i matrice

a = [1,2,3,4,5,6,7,8,9,10]
print(a)
print(type(a))

A = [[1,2,3], [4,5,6]]
print(A)

print('First item in a ', a[0], ' in A ', A[0])
print('Last item in a ', a[-1], ' in A ', A[-1])

print('First item in a ', a[:3])
print('Last item in a ', a[-3:])
print('Start at 4th item in a', a[3:])

print(a[::3][2:4])
print(A[0][1])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>
[[1, 2, 3], [4, 5, 6]]
First item in a  1  in A  [1, 2, 3]
Last item in a  10  in A  [4, 5, 6]
First item in a  [1, 2, 3]
Last item in a  [8, 9, 10]
Start at 4th item in a [4, 5, 6, 7, 8, 9, 10]
[7, 10]
2


In [29]:
print('Length of list', len(a))
print('Largest number in list', max(a))
print('Smallest number', min(a))
print('Median', np.median(a))

print('The largest number in the first list is ', max(a), 'and is found at index ', np.argmax(a))

Length of list 10
Largest number in list 10
Smallest number 1
Median 5.5
The largest number in the first list is  10 and is found at index  9


In [30]:
print(a)
a.append(4)
print(a)
print(np.sort(a))
print(np.unique(a))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 4]
[ 1  2  3  4  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
a_v = np.array(a)
print(a_v)
print(type(a_v))

[ 1  2  3  4  5  6  7  8  9 10  4]
<class 'numpy.ndarray'>


In [33]:
#Vektori i matrice
b = np.array([1,3,5])
print(b)
print(b.shape)

b = np.array([[1,3,5]]) #vektor vrsta
print(b)
print(b.shape)

c = np.array([[1],[3],[5]]) #vektor kolone
print(c)
print(c.shape)

A = np.matrix([[1,3,5],[2,4,8]])
print('\n', A)
print(A.shape)
print(type(A))

B = np.array([[1,3,5],[2,4,6]])
print('\n',B)
print(B.shape)
print(type(B))

C = np.transpose(B)
print(C.shape)

D = A + B
print(D)
print(type(D))

[1 3 5]
(3,)
[[1 3 5]]
(1, 3)
[[1]
 [3]
 [5]]
(3, 1)

 [[1 3 5]
 [2 4 8]]
(2, 3)
<class 'numpy.matrix'>

 [[1 3 5]
 [2 4 6]]
(2, 3)
<class 'numpy.ndarray'>
(3, 2)
[[ 2  6 10]
 [ 4  8 14]]
<class 'numpy.matrix'>


In [37]:
z = np.ones((2,3))
print(z)

k = np.zeros(5)
print(k)
k = np.zeros((3,3))
print(k)

e = np.eye(4,4) 
print(e)

[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
print(b)
print(b[0])
print(b[0,0])
print(b[0,-1])
print(b[0,-2:])

print(B)
print(B[1][2])
print(B[1,2])

[[1 3 5]]
[1 3 5]
1
5
[3 5]
[[1 3 5]
 [2 4 6]]
6
6


In [39]:
print(len(b))
print(b.size)
print(b.shape)

1
3
(1, 3)


In [40]:
b = b.tolist()
print(type(b))

<class 'list'>


In [42]:
# FOR

for i in range(5):
    print(i)

0
1
2
3
4


In [43]:
for i in range(0,5):
    print(i)

0
1
2
3
4


In [44]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9
10
4


In [45]:
output = []

for i in range(5):
    output.append(i**2)
output

[0, 1, 4, 9, 16]

In [46]:
output2 = [i**2 for i in range(5)]
output2

[0, 1, 4, 9, 16]

In [47]:
output3 = [i**2 for i in range(10) if i%2==0]
output3

[0, 4, 16, 36, 64]

In [48]:
L1 = [1,2,3]
L2 = ['x', 'y', 'z']
L3 = zip(L1, L2)

print(L3)
print(list(L3))

[(1, 'x'), (2, 'y'), (3, 'z')]


In [49]:
for list1, list2 in zip(L1, L2):
    print(list1, list2)

1 x
2 y
3 z


In [50]:
print([(x, y) for x, y in zip(L1, L2)])

[(1, 'x'), (2, 'y'), (3, 'z')]


In [ ]:
# IF ELSE

In [53]:
if 1 == 1:
    print('One equal one')

One equal one


In [54]:
if 1 < 0:
    print('One is less then zero')
else:
    print('One does not equal to zero')

One does not equal to zero


In [55]:
if 1 != 1:
    print('One does not equal to one')
elif 1 == 0:
    print('One is equal to zero')
else:
    print('One does not equal to zero')

One does not equal to zero


In [60]:
if (1 == 1 and 0 < 1):
    print('and operator')
    
if (1 ==1 or 0 == 1):
    print('or operator')

and operator
or operator


In [61]:
# WHILE

i = 0

while i < 5:
    print(i)
    i += 1
print(i)

0
1
2
3
4
5


In [62]:
# FUNCTIONS

def SimpleAdd2(N1, N2):
    return N1 + N2

def SimpleAdd3(N1 = 2, N2 = 2):
    return N1 + N2

print(SimpleAdd2(2, 5))

print(SimpleAdd3(1, 2))

print(SimpleAdd3())

7
3
4
